# Generated by Django 3.2.9 on 2022-11-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finished', models.BooleanField()),
                ('id_player1', models.IntegerField()),
                ('id_player2', models.IntegerField()),
                ('board', models.CharField(default='000000000', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('actual_game', models.IntegerField(blank=True, null=True)),
                ('won_games', models.IntegerField(default=0)),
                ('lost_games', models.IntegerField(default=0)),
            ],
        ),
    ]
