# Generated by Django 3.2.9 on 2022-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttApp', '0002_auto_20221122_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id_player2',
            field=models.IntegerField(null=True),
        ),
    ]
