# Generated by Django 3.2.9 on 2022-11-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tttApp', '0004_game_turn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
