# Generated by Django 3.2.9 on 2022-11-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tttApp', '0008_alter_user_actual_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tied_games',
            field=models.IntegerField(default=0),
        ),
    ]
